name: CI/CD
on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # 开启手动部署
  workflow_dispatch:

jobs:
  build:
    name: Auto CI/CD
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15]    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
            
      - name: Build && Publish
        run: | 
          cd ./docker
          sh publish.sh
      
      - name: Boot
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOYER }}
          password: ${{ secrets.DEPLOY_PWD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: | 
            cd honghuang/docker
            git checkout master
            git pull

            sh boot.sh